services:
  web1:
    build: .
    ports:
      - "3001:3000"
    environment:
      - PORT=3000
      - APP_NAME=web1
  web2:
    build: .
    ports:
      - "3002:3000"
    environment:
      - PORT=3000
      - APP_NAME=web2
